### ISSUE TITLE
issue trying to add simple node

### ISSUE THREAD

**Issue by looooo** [wonderworks-software/PyFlow#52]
I observe this by adding a simple v3Create node. Not sure if I am doing something wrong.

```
[ERROR 21:22:13]: getInputWidget() got an unexpected keyword argument 'pinAnnotations'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/App.py", line 221, in onRequestFillProperties
toolInstance.assignPropertiesWidget(propertiesFillDelegate)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Tools/PropertiesTool.py", line 58, in assignPropertiesWidget
propertiesFillDelegate(self.propertiesWidget)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UINodeBase.py", line 1271, in createPropertiesWidget
self.createInputWidgets(inputsCategory)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UINodeBase.py", line 1290, in createInputWidgets
w = createInputWidget(inp.dataType, dataSetter, inp.defaultValue(), inp.getInputWidgetVariant(), pinAnnotations=inp._rawPin.annotationDescriptionDict)
File "/home/k/projects/PyFlow/PyFlow/UI/Widgets/InputWidgets.py", line 128, in createInputWidget
pinInputWidget = factory(dataType, dataSetter, defaultValue, widgetVariant, **kwds)
TypeError: getInputWidget() got an unexpected keyword argument 'pinAnnotations'
```

**Comment by IlgarLunin** [comment]
Mine works fine. Check if you are using latest version. And as i understand you are under linux?

**Comment by IlgarLunin** [comment]
Yes, i have it on ubuntu as well
